import React from 'react';
import ProjectCard from './components/ProjectCard';
import statusData from './data/status.json';

function App() {
    return (
        <div className="min-h-screen bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
            <div className="max-w-7xl mx-auto">
                <div className="text-center mb-12">
                    <h1 className="text-4xl font-extrabold text-gray-900 tracking-tight mb-2">
                        The AI Projects Hub
                    </h1>
                    <p className="text-lg text-gray-600">
                        Centralized Command Center & Peace of Mind Dashboard
                    </p>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                    {statusData.map((project) => (
                        <ProjectCard key={project.id} project={project} />
                    ))}
                </div>

                <div className="mt-12 text-center text-sm text-gray-400">
                    <p>Auto-generated by Antigravity Agent</p>
                    <p className="mt-1">Last Sync: {new Date().toLocaleTimeString()}</p>
                </div>
            </div>
        </div>
    );
}

export default App;
